LOG_TENSORBOARD = True

CBOW_INPUT_LENGTH = 4

BATCH_LOG_INTERVAL = 200
VALID_PREDICTION_SAMPLE_RATE = 2
OPTIMIZER_ADAM_LR = 1.0
EPOCHS = 54
BATCH_SIZE = 8

SHUFFLE_DATA = True
APPLY_LR_SCHEDULER = True

# Data augmentation
APPLY_SCALE_AUGMENTATION = True